# SwiftLint Configuration for BoardMate iOS
# Optimized for TCA patterns and modern Swift development

# Rules to enable
opt_in_rules:
  - accessibility_label_for_image
  - array_init
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_enum_raw_value
  - extension_access_modifier
  - fallthrough
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - yoda_condition

# Rules to disable
disabled_rules:
  - todo # Allow TODO comments for development
  - unused_optional_binding # Can be useful in TCA patterns
  - large_tuple # TCA state can have large tuples

# Configuration for specific rules
line_length:
  warning: 120
  error: 140
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

cyclomatic_complexity:
  warning: 12
  error: 20

nesting:
  type_level:
    warning: 3
    error: 4

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  allowed_symbols: ["_"]
  validates_start_with_lowercase: error

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50

# Exclusions
excluded:
  - Carthage
  - Pods
  - .build
  - .swiftpm
  - Package.swift
  - "*/Generated/*"
  - "*/Derived/*"
  - "*/.build/*"
  - "*/build/*"
  - DerivedData

# Include patterns
included:
  - rulebook-kit/Sources
  - rulebook-kit/Tests

# Custom rules for TCA patterns
custom_rules:
  tca_action_naming:
    name: "TCA Action Naming"
    regex: '(case\s+)([a-z][a-zA-Z0-9]*)(Action\s*(\(|$))'
    message: "TCA actions should not have 'Action' suffix"
    severity: warning
  
  tca_state_properties:
    name: "TCA State Properties"
    regex: '(struct\s+\w*State[\s\S]*?)(var\s+[a-zA-Z_][a-zA-Z0-9_]*\s*:\s*[^=\n]*=)'
    message: "TCA State properties should prefer let over var when possible"
    severity: warning

# Analyzer rules
analyzer_rules:
  - unused_declaration
  - unused_import
  - explicit_self

# Reporter configuration
reporter: "xcode"

# Only fail build on errors, not warnings
strict: false